### ISSUE TITLE
Newbie user need help for proxy/cloudflare/https

### ISSUE THREAD

**Issue by id4vip** [HuJK/bitwarden_gcloud_cloudflare#1]
Hi,
Thanks for providing a this great arrangement. I just want to request you that please help us to make arrangement without the help of cloud flare. As for DDclient they are providing only if we have paid service or domain from them. Please elaborate your mechanism only with free available services like duckdns, lets encrypt etc.
for free domains & cloudflare service i am geting this "error": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."

also one expert suggest me swag :-
https://docs.linuxserver.io/general/swag

**Comment by HuJK** [comment]
You need to add the domain on Cloudflare's panel instead of using third party panel.

If you want a cloudflare-free solution, you should use original repo instead of mine https://github.com/dadatuputi/bitwarden_gcloud
